[package]
name = "webcomponent"
version = "0.1.3"
authors = ["Richard <Richard>"]
edition = "2018"
license = "MIT"
description = "A simple web component framework"

[dependencies]
callback = "0.0.1"
cstring = "0.0.1"
globals = "0.0.1"
